# This is the Netlify.toml file for the Bikes Shot website.
# The redirects were added on 2023-07-19 to ensure that the SEO for the pages
# is not affected when the pages are moved to new URLs.

[[redirects]]
from = "/kits-y-paquetes-bikes-shot/"
to = "/index.html#promociones"
status = 301
force = true

[[redirects]]
from = "/silicon-lube/"
to = "/silicon-lube.html"
status = 301
force = true

[[redirects]]
from = "/chain-wax/"
to = "/chain-wax.html"
status = 301
force = true

[[redirects]]
from = "/chain-wax-cera-lubricante-de-cadena-para-terrenos-secos/"
to = "/chain-wax.html"
status = 301
force = true

[[redirects]]
from = "/chain-lube/"
to = "/chain-lube.html"
status = 301
force = true

[[redirects]]
from = "/bio-desengrasante/"
to = "/bio-desengrasante.html"
status = 301
force = true

[[redirects]]
from = "/brake-cleaner/"
to = "/brake-cleaner.html"
status = 301
force = true

[[redirects]]
from = "/lubricante-multi-usos/"
to = "/lubricante-multi-usos.html"
status = 301
force = true

[[redirects]]
from = "/para-motocicletas/"
to = "/index.html"
status = 301
force = true

[[redirects]]
from = "/para-bicicletas-profesionales/"
to = "/index.html"
status = 301
force = true

[[redirects]]
from = "/contacto/"
to = "/index.html"
status = 301
force = true

[[redirects]]
from = "/motocicletas/lubricantes-y-aceites-para-cadena-de-motocicleta/"
to = "/lubricantes-y-aceites-para-cadena-de-motocicleta.html"
status = 301
force = true

[[redirects]]
from = "/bicicletas/lubricantes-para-bicicletas-de-montana-y-ruta/"
to = "/lubricantes-para-bicicletas-de-montana.html"
status = 301
force = true

[[redirects]]
from = "/inicio/"
to = "/index.html"
status = 301
force = true

[[redirects]]
from = "/nuestros-productos/"
to = "/index.html"
status = 301
force = true